### ISSUE TITLE
results not consistent with FGS+ and prodigal

### ISSUE THREAD

**Issue by jianshu93** [unipept/FragGeneScanRs#3]
Hello,

A benchmark test using FGS+ and prodigal showed that this FragGeneScanRs is not consistent with FGS+ and prodigal for most of the time (e.g. gene position predicted is very different) while FGS+ and prodigal  are consistent with each other. I attache the genome I was using. There might be something wrong with the model or parameter setup.

.out is for rust version and .prodigal.gff is from prodigal

commands are:

FragGeneScanRs -s NTO_MAG_1.fasta -p 8 -t complete -w 1 -o NTO_MAG_1_gene

FGS+ -s NTO_MAG_1.fasta -p 8 -t complete -w 1 -o NTO_MAG_1_gene+

prodigal -i NTO_MAG_1.fasta -p meta -f gff -o NTO_MAG_1_prodigal.gff -a NTO_MAG_1.prodigal.faa -d NTO_MAG_1.prodigal.fna

[NTO_MAG_1.fasta.zip](https://github.com/unipept/FragGeneScanRs/files/7172085/NTO_MAG_1.fasta.zip)

[NTO_MAG_1_gene.out.zip](https://github.com/unipept/FragGeneScanRs/files/7172129/NTO_MAG_1_gene.out.zip)
[NTO_MAG_1_prodigal.gff.zip](https://github.com/unipept/FragGeneScanRs/files/7172130/NTO_MAG_1_prodigal.gff.zip)

Thanks,

Jianshu

**Comment by bmesuere** [comment]
Thank you very much for your report. At a glance, it seems that the end positions and frames mostly match, but that there's a difference in starting position. We have not seen this before (but have mostly worked with short reads ourselves).
 
We'll look into this!

**Comment by jianshu93** [comment]
Many thanks! It would nice if you can also add gff output. It should be quite easy based on the .out file I think. A few lines at most to do that. It is a great rewritten by the way. When this bug is fixed I think it will replace prodigal/metaGeneMark and FragGeneScan in term of both speed and user experience especially for meragenomic studies.

Thanks,

Jianshu

**Comment by jianshu93** [comment]
[NTO_MAG_1_gene.gff.zip](https://github.com/unipept/FragGeneScanRs/files/7181547/NTO_MAG_1_gene.gff.zip)



I still do not have the same positions for FGSrs

Jianshu

**Comment by jianshu93** [comment]
[Archive.zip](https://github.com/unipept/FragGeneScanRs/files/7842053/Archive.zip)
This is Huge difference for a complete genome. I am Surprised the complete genome model is so bad.

Jianshu
